### ISSUE TITLE
PyPy compatability

### ISSUE THREAD

**Issue by sils1297** [hannosch/python-gettext#6]
hey, python-gettext doesn't seem to work with pypy3 on linux. See https://circleci.com/gh/coala-analyzer/coala/1987 , build on node 3.

**Comment by hannosch** [comment]
The test failure shows a problem in Python's own gettext module, not this project which is confusingly named python-gettext. I'd guess the reload(module) might be the problem in the test, as not all Python code deals well with being reloaded.
