### ISSUE TITLE
Please fix error while compiling

### ISSUE THREAD

**Issue by serge73** [hannosch/python-gettext#7]
Please fix error while compiling /usr/local/Plone504/buildout-cache/eggs/**python_gettext-3.0-py2.7.egg/pythongettext/tests/test5.po**

-msgstr "føø
-bår"
**+msgstr "føø bår"**

**Comment by hannosch** [comment]
This is a test file with a deliberate syntax error in it. Nobody outside this projects test suite should try to compile the file.
