### ISSUE TITLE
Please fix error while compiling 2

### ISSUE THREAD

**Issue by serge73** [hannosch/python-gettext#8]
Error while compiling /usr/local/Plone504/buildout-cache/eggs/**python_gettext-3.0-py2.7.egg/pythongettext/tests/test_escape.po**

msgid "msgid3"
-msgstr "Hellø "bar\"" 
+msgstr "Hellø \"bar\""

**Comment by hannosch** [comment]
This is a test file with a deliberate syntax error in it. Nobody outside this projects test suite should try to compile the file.
